### ISSUE TITLE
please upload 1.18.2 and 1.19 versions to CurseForge

### ISSUE THREAD

**Issue by MSandro** [ENDERZOMBI102/MapForce#1]
Hello, thanks for your work, I really like this mod.
I would like to use it in my 1.18.2 Modpack, but I can't because the mod is not available on CurseForge.
tyvm.

**Comment by MSandro** [comment]
or am I allowed to include the mod as a embedded Jar file in my Mod Sky-Island Generator?
https://github.com/MSandro/skyislands

**Comment by ENDERZOMBI102** [comment]
you are allowed, yes
just add a small note on the readme that you’re using it, its all i ask

**Comment by ENDERZOMBI102** [comment]
no updates, assume its stale
